### ISSUE TITLE
Create logic.js file with common functions to manage the current project

### ISSUE THREAD

**Issue by Prelle** [Prelle/Team13Project1#9]
AS A developer creating the project management app
I NEED common functions to exist that allow me to create and edit the existing project
SO THAT I can use these functions when writing the webpages for the application

Acceptance Criteria

A logic.js file should exist
The logic file should contain functions to getCurrentProject, setCurrentProject and updateCurrentProject.
getCurrentProject should return the project if it exists in localStorage, or null if it does not exist
createCurrentProject should create the project if it does not exist, or return an error if a project already exists
 parameters: project name, project description
 The project should be created with an empty array of tasks
updateCurrentProject should overwrite the existing project if it exists, or return an error if a project does not exist
 parameters: project name, project description, array of tasks

**Comment by Jerome4star** [comment]
Did not write the updateCurrentProject function
